version: '3.8'

services:
  automator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Pass these environment variables from your host system
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - OPENWEIGHTS_API_KEY=${OPENWEIGHTS_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
    volumes:
      # Mount a volume for workspaces to persist data
      - automator_workspaces:/root/.automator/workspaces
    # Override default command if needed
    # command: ["sh", "-c", "cd /app/automator && uv run python examples/quickstart.py"]

volumes:
  automator_workspaces: