[project]
name = "talk-to-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
    "openai>=1.76.0",
    "pyyaml>=6.0.2",
]
